import assert from "node:assert/strict";
import test from "node:test";
import { JSDOM } from "jsdom";
import { bindTreeView } from "../src/tree-view-dom.js";
import { bindAccordion } from "../src/accordion-dom.js";
import { bindSwitch } from "../src/switch-dom.js";

test("tree, accordion and switch adapters sync ARIA", () => { const dom = new JSDOM(`<div id="tree"><button data-rui-treeitem>Root</button></div><div id="accordion"><section id="one" data-rui-accordion-item><button data-rui-accordion-trigger>One</button><div id="one-content" data-rui-accordion-content>Content</div></section></div><button id="switch" data-rui-switch>Switch</button>`); const tree = bindTreeView(dom.window.document.querySelector("#tree") as HTMLElement); assert.equal(dom.window.document.querySelector("#tree")?.getAttribute("role"), "tree"); const accordion = bindAccordion(dom.window.document.querySelector("#accordion") as HTMLElement); dom.window.document.querySelector("[data-rui-accordion-trigger]")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); assert.equal((dom.window.document.querySelector("[data-rui-accordion-content]") as HTMLElement).hidden, false); const toggle = bindSwitch(dom.window.document.querySelector("#switch") as HTMLElement); toggle.controller.toggle(); assert.equal(dom.window.document.querySelector("#switch")?.getAttribute("aria-checked"), "true"); tree.destroy(); accordion.destroy(); toggle.destroy(); });

test("DOM adapters handle refresh, unrelated events and repeated destroy", () => { const dom = new JSDOM(`<div id="tree"><button data-rui-treeitem>Root</button><button data-rui-treeitem data-parent="tree-0">Child</button></div><div id="accordion"><section id="empty" data-rui-accordion-item><button data-rui-accordion-trigger>Empty</button></section></div><button id="switch" data-rui-switch data-disabled="true">Switch</button>`); const treeRoot = dom.window.document.querySelector("#tree") as HTMLElement; const tree = bindTreeView(treeRoot); treeRoot.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "PageDown", bubbles: true })); treeRoot.querySelector("[data-rui-treeitem]")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); tree.destroy(); tree.destroy(); const accordion = bindAccordion(dom.window.document.querySelector("#accordion") as HTMLElement); dom.window.document.querySelector("#accordion")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); accordion.destroy(); accordion.destroy(); const toggle = bindSwitch(dom.window.document.querySelector("#switch") as HTMLElement); toggle.controller.handleKeyDown({ key: " " } as KeyboardEvent); toggle.destroy(); toggle.destroy(); });

test("accordion adapter supports missing content and multiple sections", () => { const dom = new JSDOM(`<div id="accordion"><section id="one" data-rui-accordion-item><button data-rui-accordion-trigger>One</button></section><section id="two" data-rui-accordion-item><button>Two</button><div id="two-content" data-rui-accordion-content>Two content</div></section><section id="disabled" data-rui-accordion-item data-disabled="true"><button>Disabled</button></section><section data-rui-accordion-item><button>Orphan</button></section></div>`); const root = dom.window.document.querySelector("#accordion") as HTMLElement; const binding = bindAccordion(root, { multiple: true }); root.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); root.querySelector("#one button")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); root.querySelector("#two button")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); root.querySelector("#disabled button")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); binding.destroy(); binding.destroy(); });
