import assert from "node:assert/strict";
import test from "node:test";
import { JSDOM } from "jsdom";
import { RadioGroupController } from "../src/radio-group.js";
import { bindRadioGroup } from "../src/radio-group-dom.js";
import { ToggleGroupController } from "../src/toggle-group.js";
import { bindToggleGroup } from "../src/toggle-group-dom.js";

const items = [{ id: "one", value: "one", label: "One" }, { id: "two", value: "two", label: "Two" }, { id: "three", value: "three", label: "Three", disabled: true }];
test("radio group selects one item and navigates", () => { const radio = new RadioGroupController(); radio.setItems(items); assert.equal(radio.select("one"), true); radio.handleKeyDown({ key: "ArrowRight" } as KeyboardEvent); assert.equal(radio.getState().selectedId, "two"); assert.equal(radio.select("three"), false); radio.destroy(); });
test("toggle group supports multiple selection", () => { const toggle = new ToggleGroupController(); toggle.setItems(items); toggle.toggle("one"); toggle.toggle("two"); assert.deepEqual(toggle.getState().selectedIds, ["one", "two"]); toggle.handleKeyDown({ key: "ArrowRight" } as KeyboardEvent); toggle.destroy(); });
test("radio and toggle DOM adapters sync ARIA", () => { const dom = new JSDOM(`<div id="radio"><button data-rui-radio data-value="one">One</button><button data-rui-radio data-value="two">Two</button></div><div id="toggle"><button data-rui-toggle>Bold</button></div>`); const radio = bindRadioGroup(dom.window.document.querySelector("#radio") as HTMLElement); radio.controller.select("radio-0"); assert.equal(dom.window.document.querySelector("#radio")?.getAttribute("role"), "radiogroup"); assert.equal(dom.window.document.querySelector("[data-rui-radio]")?.getAttribute("aria-checked"), "true"); const toggle = bindToggleGroup(dom.window.document.querySelector("#toggle") as HTMLElement, "single"); dom.window.document.querySelector("[data-rui-toggle]")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); assert.equal(dom.window.document.querySelector("[data-rui-toggle]")?.getAttribute("aria-pressed"), "true"); radio.destroy(); toggle.destroy(); });

test("radio and toggle adapters cover disabled, nested and destroy paths", () => { const dom = new JSDOM(`<div><div id="radio"><button data-rui-radio data-disabled="true">Disabled</button><span><button data-rui-radio>Nested</button></span></div><div id="toggle"><button data-rui-toggle data-disabled="true">Disabled</button><span><button data-rui-toggle>Nested</button></span></div></div>`); const radioRoot = dom.window.document.querySelector("#radio") as HTMLElement; const toggleRoot = dom.window.document.querySelector("#toggle") as HTMLElement; const radio = bindRadioGroup(radioRoot); const toggle = bindToggleGroup(toggleRoot); radioRoot.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "PageDown", bubbles: true })); toggleRoot.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "PageDown", bubbles: true })); radioRoot.querySelector("[data-rui-radio]")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); toggleRoot.querySelector("[data-rui-toggle]")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true })); radio.destroy(); radio.destroy(); toggle.destroy(); toggle.destroy(); });

test("empty radio and toggle roots use generated ids safely", () => { const dom = new JSDOM(`<div><button data-rui-radio></button></div><div><button data-rui-toggle></button></div>`); const radioRoot = dom.window.document.querySelectorAll("div")[0] as HTMLElement; const toggleRoot = dom.window.document.querySelectorAll("div")[1] as HTMLElement; const radio = bindRadioGroup(radioRoot); const toggle = bindToggleGroup(toggleRoot); radioRoot.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "ArrowDown", bubbles: true })); toggleRoot.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "ArrowDown", bubbles: true })); const radioItem = radioRoot.querySelector("[data-rui-radio]") as HTMLElement; radioItem.click(); const toggleItem = toggleRoot.querySelector("[data-rui-toggle]") as HTMLElement; toggleItem.click(); radio.destroy(); toggle.destroy(); });
